# from tkinter import*
# from tkinter import ttk
# root=Tk()
# pw=ttk.PanedWindow(root,orient=VERTICAL)
# pw.pack(fill=BOTH,expand=TRUE,side=TOP)
# pw=ttk.PanedWindow(root,orient=HORIZONTAL)
# pw.pack(fill=BOTH,expand=TRUE)
# frame1=ttk.Frame(pw,relief=SUNKEN)
# frame2=ttk.Frame(pw,relief=SUNKEN)
# pw.add(frame1,weight=1)
# pw.add(frame2,weight=5)
# # pw2.add(frame1,weight=3)
# # pw2.add(frame2,weight=1)
# root.geometry("400x240")
# root.title("pythonlobby")
# root.mainloop()
